import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import { TLanguage } from '@/types/common';
import type { Metadata, Viewport } from 'next';
import { Be_Vietnam_Pro as FontSans } from 'next/font/google';
import { ReactNode } from 'react';

import Providers from '@/components/providers';
import '@/styles/globals.css';
import { getDictionary } from './dictionaries';
import Header from '@/components/shared/header';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Go Bike',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'vi' }];
}

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: {
    lang: TLanguage;
  };
}>) {
  const dictionary = await getDictionary(params.lang);
  return (
    <html lang={params.lang}>
      <body className={cn('min-h-screen w-full', fontSans.variable, fontSans.className)}>
        <Providers dictionary={dictionary}>
          <Header lang={params.lang} />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
