import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import { ReactNode } from 'react';
import { TLanguage } from '@/types/common';

import '@/styles/globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Go Bike',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'vi' }];
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: {
    lang: TLanguage;
  };
}>) {
  return (
    <html lang={params.lang}>
      <body className={cn('min-h-screen', fontSans.variable)}>{children}</body>
    </html>
  );
}
